# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9919a1928f1778507bd4ebf1c9ce973fd8957fe74f07ad59d914b5cbe5c075af211f2ae0409ea2cf58228c94f19422c46b2d3b7a33c78f964f3a0efd68b51732

test:
  secret_key_base: 2ed68262c99ccd164999e56ecd9c396e68b63e37420a270311467a6344e283be7e79b735d28affd7743de757f1f8fdfc53488588fcdcd74e65c4c6f9f10e531f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
